name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup build directory
      run: mkdir build
    - name: CMake
      run: cmake -G "Unix Makefiles" -S . -B build     
    - name: make
      run: make --directory=build
