name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build and test

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup build directory
      run: mkdir build && cd build
    - name: CMake
      run: cmake -G "Unix Makefiles" ..
    - name: make
      run: make
    - name: CTest
      run: ctest
