name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup build directory
      run: mkdir build
    - name: CMake
      run: cmake -G "Unix Makefiles" -S . -B build
    - name: make
      run: make --directory=build
    - name: CTest
      run: cd build && ctest
